# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target '团购项目' do
  # Uncomment this line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

# Pods for 团购项目
pod 'Masonry', '~> 1.0.2'
pod 'SDWebImage', '~> 3.8.2'
pod 'AFNetworking', '~> 3.1.0'
pod 'SVProgressHUD', '~> 2.0.3'
pod 'BEMCheckBox', '~> 1.2.1'
pod 'MJRefresh', '~> 3.1.12'
pod 'SDCycleScrollView', '~> 1.65'
pod 'MJExtension', '~> 3.0.13'
pod 'JSBadgeView', '~> 1.4.1'
pod 'PYSearch', '~> 0.3.8'

end
